import React from 'react';
import { Alert, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { useCart } from '../../context/CartContext';
import { Button, EmptyState, ScreenHeader } from '../../components/UI';
import { theme } from '../../theme';

export default function CartScreen({navigation}:any){
 const {items,change,remove,total}=useCart();
 if(!items.length) return <SafeAreaView style={styles.container}><ScreenHeader title="Your Cart"/><EmptyState icon="shopping-bag" title="Your cart is empty" message="Add something delicious from the menu." actionTitle="Browse Menu" onAction={()=>navigation.navigate('Home')}/></SafeAreaView>;
 return <SafeAreaView style={styles.container}><ScreenHeader title="Your Cart" right={<TouchableOpacity onPress={()=>items.forEach(i=>remove(i.id))}><Text style={styles.clear}>Clear</Text></TouchableOpacity>}/><ScrollView contentContainerStyle={styles.content}>{items.map(i=><View key={i.id} style={styles.item}><View style={styles.itemMain}><Text style={styles.name}>{i.name}</Text><Text style={styles.price}>₹{i.price} each</Text></View><View style={styles.controls}><TouchableOpacity onPress={()=>change(i.id,-1)} style={styles.qty}><Feather name="minus" size={15}/></TouchableOpacity><Text style={styles.qtyText}>{i.quantity}</Text><TouchableOpacity onPress={()=>change(i.id,1)} style={styles.qty}><Feather name="plus" size={15}/></TouchableOpacity><TouchableOpacity onPress={()=>remove(i.id)} style={styles.delete}><Feather name="trash-2" size={17} color={theme.colors.danger}/></TouchableOpacity></View><Text style={styles.subtotal}>₹{i.price*i.quantity}</Text></View>)}</ScrollView><View style={styles.footer}><View style={styles.totalRow}><Text style={styles.totalLabel}>Total</Text><Text style={styles.total}>₹{total}</Text></View><Button title="Proceed to Checkout" onPress={()=>navigation.navigate('Checkout')}/></View></SafeAreaView>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:theme.colors.background},content:{padding:20,paddingBottom:130},clear:{color:theme.colors.danger,fontWeight:'700'},item:{backgroundColor:'#FFF',borderRadius:15,padding:15,marginBottom:10,flexDirection:'row',alignItems:'center',gap:10,elevation:1},itemMain:{flex:1},name:{fontSize:14,fontWeight:'800'},price:{fontSize:11,color:theme.colors.textMuted,marginTop:3},controls:{flexDirection:'row',alignItems:'center',gap:9},qty:{width:28,height:28,borderRadius:14,backgroundColor:theme.colors.primaryLight,alignItems:'center',justifyContent:'center'},qtyText:{fontWeight:'800',minWidth:15,textAlign:'center'},delete:{marginLeft:4},subtotal:{fontWeight:'900',width:48,textAlign:'right'},footer:{position:'absolute',bottom:0,left:0,right:0,backgroundColor:'#FFF',padding:20,borderTopWidth:1,borderTopColor:'#EEE'},totalRow:{flexDirection:'row',justifyContent:'space-between',marginBottom:8},totalLabel:{fontSize:14,color:theme.colors.textSecondary},total:{fontSize:22,fontWeight:'900'}});
